<?php
require_once __DIR__ . '/../includes/auth.php';
requireRole('technician');
$user = currentUser();
$stmt = $pdo->prepare("SELECT b.*, c.full_name AS customer_name, c.phone, c.address, s.service_name FROM Booking b JOIN Customer c ON b.customer_id = c.customer_id JOIN Services s ON b.service_id = s.service_id WHERE b.tech_id_1 = ? OR b.tech_id_2 = ? ORDER BY b.booking_date, b.booking_time");
$stmt->execute([$user['id'], $user['id']]);
$jobs = $stmt->fetchAll();
?>
<!DOCTYPE html>
<html lang="th"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>งานของช่าง</title><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fontsource/kanit@5.0.0/thai-400.css"></head>
<body class="min-h-screen bg-slate-100 p-4"><main class="mx-auto w-full max-w-4xl"><header class="mb-5 flex items-center justify-between rounded-2xl bg-blue-900 p-5 text-white"><div><h1 class="text-xl font-bold">งานของฉัน</h1><p class="text-sm text-white/70"><?= htmlspecialchars($user['name']) ?></p></div><a href="/web_app/api/logout.php" class="rounded-lg bg-red-500 px-3 py-2 text-sm font-semibold">ออกจากระบบ</a></header><div class="space-y-4">
<?php foreach ($jobs as $job): ?><article class="rounded-2xl bg-white p-5 shadow"><div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="font-bold text-slate-800">#<?= (int)$job['booking_id'] ?> · <?= htmlspecialchars($job['service_name']) ?></h2><p class="text-sm text-slate-500"><?= htmlspecialchars($job['booking_date']) ?> เวลา <?= htmlspecialchars(substr($job['booking_time'], 0, 5)) ?></p></div><span class="rounded-full bg-blue-100 px-3 py-1 text-sm text-blue-800"><?= htmlspecialchars($job['status_service']) ?></span></div><div class="mt-4 space-y-1 text-sm text-slate-600"><p>ลูกค้า: <?= htmlspecialchars($job['customer_name']) ?> · <?= htmlspecialchars($job['phone'] ?? '-') ?></p><p>สถานที่: <?= htmlspecialchars($job['address'] ?? '-') ?></p><p>อาการ: <?= nl2br(htmlspecialchars($job['problem_description'] ?? '-')) ?></p></div><form method="POST" action="/web_app/technician/update_status.php" class="mt-4 flex flex-wrap gap-2"><input type="hidden" name="booking_id" value="<?= (int)$job['booking_id'] ?>"><select name="status_service" class="rounded-lg border px-3 py-2 text-sm"><option>รับงานแล้ว</option><option>กำลังเดินทาง</option><option>กำลังซ่อม</option><option>เสร็จสิ้น</option></select><button class="rounded-lg bg-blue-900 px-4 py-2 text-sm font-semibold text-white">อัปเดตสถานะ</button></form></article><?php endforeach; ?>
<?php if (!$jobs): ?><div class="rounded-2xl bg-white p-8 text-center text-slate-500 shadow">ยังไม่มีงานที่ได้รับมอบหมาย</div><?php endif; ?></div></main></body></html>
